# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fe4645c473d33be3bf821944e64635cc4380d1f2d67a6868dd6cb2bbd6379d017ab58cb9e04125adcae8d771086d2fba1e2ed62c2575d09622392c2c30da4567

test:
  secret_key_base: 4ac316da5f0dd8290fcb3f9c3a4433f9d33658db538113d081e607135e79307ed0757dbf5073cd49642da25e91bb5b1b13407cd0b289b9c5ace8d8230b1846f5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
